name: Pull Request on Branch Push
on:
  push:
    branches:
      - hotfix

jobs:
  auto-pull-request:
    if: github.event.pull_request.merged == 'true'
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "dev"
          PULL_REQUEST_DRAFT: "true"
